
export const LOGGED_IN = "LOGGED_IN"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"